# Generated by Django 2.1.2 on 2018-11-12 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0002_auto_20181107_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=20)),
                ('ciudad_sede', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='rodillera',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='estado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='tipo_bicicleta',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='ubicacion',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='precio_equipamiento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='tipo_equipamiento',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='aro',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
