# Generated by Django 2.1.2 on 2018-11-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20181112_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='tipo_bicicleta',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
