# Generated by Django 2.1.2 on 2018-11-15 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20181115_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='tipo_bicicleta',
            field=models.CharField(choices=[('MONT', 'Montaña'), ('URB', 'Urbana'), ('RU', 'Ruta')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='bicicleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Bicicleta'),
        ),
    ]
