# Generated by Django 2.1.2 on 2018-11-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20181112_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='tipo_bicicleta',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
