# Generated by Django 2.1.2 on 2018-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20181112_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_catalogo', models.CharField(max_length=50)),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_bicicletas'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tipo_bicicleta',
            field=models.CharField(choices=[('MONT', 'Montaña'), ('URB', 'Urbana'), ('RU', 'Ruta')], default=None, max_length=20),
        ),
    ]
