# Generated by Django 2.1.2 on 2018-11-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20181112_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Catalogo'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Catalogo'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Catalogo'),
        ),
    ]
