# Generated by Django 2.1.2 on 2018-11-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20181112_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='user',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='user',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='bicicleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Bicicleta'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='equipamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Equipamiento'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Sede'),
        ),
    ]
