# Generated by Django 2.1.2 on 2018-11-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20181115_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicicleta',
            old_name='descripcion',
            new_name='descripcion_bicicleta',
        ),
        migrations.RenameField(
            model_name='bicicleta',
            old_name='imagen',
            new_name='imagen_bicicleta',
        ),
        migrations.RenameField(
            model_name='bicicleta',
            old_name='estado',
            new_name='precio_bicicleta',
        ),
        migrations.RenameField(
            model_name='bicicleta',
            old_name='ubicacion',
            new_name='ubicacion_bicicleta',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='precio',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='estado_bicicleta',
            field=models.CharField(blank=True, choices=[('DI', 'Disponible'), ('NO', 'No diponible'), ('MA', 'Mantencion'), ('RS', 'Reservado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='descripcion_equipamiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='estado_equipamiento',
            field=models.CharField(blank=True, choices=[('DI', 'Disponible'), ('NO', 'No diponible'), ('MA', 'Mantencion'), ('RS', 'Reservado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='imagen_equipamiento',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_equipamiento'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='ubicacion_equipamiento',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='bicicleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Bicicleta'),
        ),
    ]
