# Generated by Django 2.1.2 on 2018-11-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_auto_20181115_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='tipo_catalogo',
            field=models.CharField(choices=[('BICI', 'Bicicleta'), ('EQUIP', 'Equipamiento')], max_length=50),
        ),
    ]
