# Generated by Django 2.1.2 on 2018-11-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_auto_20181115_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='id',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='id_bicicleta',
            field=models.CharField(default='DEFECTO', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='id_equipamiento',
            field=models.PositiveIntegerField(default='DEFECTO', primary_key=True, serialize=False),
        ),
    ]
